<?php

/**
 * @file
 * Drupal hooks for the commerce_uuid module.
 */

/**
 * Implements hook_entity_info_alter().
 */
function commerce_uuid_customer_entity_info_alter(&$entity_info) {
  $entity_info['commerce_customer_profile']['uuid'] = TRUE;
  $entity_info['commerce_customer_profile']['entity keys']['uuid'] = 'uuid';
  $entity_info['commerce_customer_profile']['entity keys']['revision uuid'] = 'vuuid';
}

/**
 * Implements hook_entity_uuid_load().
 */
function commerce_uuid_customer_entity_uuid_load(&$entities, $entity_type) {
  if ($entity_type == 'commerce_customer_profile') {
    entity_property_id_to_uuid($entities, 'commerce_customer_profile', array('profile_id'));
  }
}

/**
 * Implements hook_entity_uuid_presave().
 */
function commerce_uuid_customer_entity_uuid_presave(&$entity, $entity_type) {
  if ($entity_type == 'commerce_customer_profile') {
    entity_property_uuid_to_id($entity, 'commerce_customer_profile', array('profile_id'));
  }
}
